### Separated out configuration options  #### 

###### Begin Compilation Options #######

### This defines a __float128 for CINT's perusal. Necessary on 64-bit machines with fftw, probably harmless on others? 
CINTFLAGS=-DFFTW_64_BIT  

### Override the compiler here (might be helpful on older Macs or testing with multiple compilers) 
#CXX=clang++

### Force debugger on (multiple -g's don't hurt) 
CXXFLAGS += -g 
LDFLAGS += -g 

### Comment out next two lines to disable explicit vectorization 
CXXFLAGS+= -I$(VECTORDIR) -DENABLE_VECTORIZE $(ARCH_STRING) 
VECTORIZE=$(VECTORDIR) 

### For Agner Fog's vectorclass, g++ needs to use -fabi-version=0 , but clang doesn't support this option. This is likely irrelevant if vectorization not enabled 
ifeq ($(CXX),g++)
CXXFLAGS+=-fabi-version=0 
endif

### Compile time options for SineSubtract vectorization... (more info in SineSubtract.h)  #####
# Uncomment below to use floats instead of doubles (implies an extra copy and less precision, but theoretically twice the vectorization) 
#CXXFLAGS+=-DSINE_SUBTRACT_USE_FLOATS
# Uncomment below to print out time to call SineSubtract::subtractCW() 
#CXXFLAGS+=-DSINE_SUBTRACT_PROFILE
## End configuration for SineSubtract######

### Compile time options for linear algebra libs #####
# Uncomment following line to use eigen3 (heavily recommended!) 
# You can define EIGEN3_INCLUDE_DIR if you need to 
# CXXFLAGS+=-DUSE_EIGEN -I$(EIGEN3_INCLUDE_DIR)/  -I$(EIGEN3_INCLUDE_DIR)/eigen3/ 
# Uncomment following 2 lines to use armadillo (and comment out eigen)
#CXXFLAGS+=-DUSE_ARMADILLO 
#LDFLAGS +=-larmadillo 
## End linear algebra configuration


### FFT Options
# Uncomment following line to change FFTW plan creation mode to FFTW_PATIENT, 
#   which has higher up-front cost but might be faster later. Otherwise FFTW_MEASURE is used. 
#CXXFLAGS += -DFFTW_USE_PATIENT
# Uncomment following line to enable (experimental and not-yet-working) thread-safe mode
#CXXFLAGS += -DFFTTOOLS_THREAD_SAFE


###### End Compilation Options ##### # 


#####Site Specific  Flags (adjust to local site)
OUTLIBDIR          = 
OUTINCDIR          = 
SYSINCLUDES	= -I/usr/local/include
SYSLIBS         = -L/usr/local/lib
DLLSUF = ${DllSuf}
OBJSUF = ${ObjSuf}
SRCSUF = ${SrcSuf}

ifdef ANITA_UTIL_INSTALL_DIR
UTIL_LIB_DIR=${ANITA_UTIL_INSTALL_DIR}/lib
UTIL_INC_DIR=${ANITA_UTIL_INSTALL_DIR}/include
LD_UTIL=-L$(ANITA_UTIL_LIB_DIR)
INC_UTIL=-I$(ANITA_UTIL_INC_DIR)
else 
ifdef ARA_UTIL_INSTALL_DIR
UTIL_LIB_DIR=${ARA_UTIL_INSTALL_DIR}/lib
UTIL_INC_DIR=${ARA_UTIL_INSTALL_DIR}/include
LD_UTIL=-L$(ARA_UTIL_LIB_DIR)
INC_UTIL=-I$(ARA_UTIL_INC_DIR)
else
UTIL_LIB_DIR=/usr/local/lib
UTIL_INC_DIR=/usr/local/include
endif
endif


